#!/bin/bash

notify-send -t 2000 "Scratchpad" \
"o journal
n ranger
semicolon terminal
p ncpamixer
c qalculate
i tickrs
y htop
w whatsapp
k keepass
t todos (caldav-tui)
e evolution
d theme-mode-toggle
a wallpaper-random
g nightlight-toggle
u bluetooth-toggle
f caffeine-toggle
r keyboard-backlight-toggle
q network-toggle
s osd-toggle
b feishin"
