#!/bin/bash

notify-send -t 2000 "Scratchpad" \
"o journal
n ranger
semicolon terminal
p ncpamixer
c qalculate
i tickrs
y htop
w whatsapp
k keepass
t todos (caldav-tui)
d theme-mode-toggle
e evolution
b feishin"
