#!/usr/bin/env python

import requests


class PiHole(object):
    """
    Gets pihole data, using the 'summary' API request.
    """

    def __init__(self, ip_add):
        """
        Gets pihole data, using the 'summary' API request.
        """

        if not ip_add:
            return

        url = 'http://' + ip_add + '/admin/api.php?summary'

        try:
            resp = requests.get(url)
        except Exception:
            print('Invalid Host')
            return

        self.data = resp.json()


if __name__ == '__main__':
    pass
