#!/usr/bin/env bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -location 1 -xoffset 10 -yoffset 32 \
	-line-padding 4 -columns 1 -width 30 -lines 25 -padding 25 \
	-hide-scrollbar -show-icons
