#!/usr/bin/env python

import glob
import os
import shutil

shittyfiles = [
    '~/.pkg-cache',
    '~/.clangd',
    '~/.hunter',
    '~/.cache/',
    '~/.local/share/qutebrowser/',
    '~/.python_history',
    '~/.zcompdump*',
    '~/.local/share/xorg/'
    '~/.adobe',  # Flash crap
    '~/.macromedia',  # Flash crap
    '~/.recently-used',
    '~/.local/share/recently-used.xbel',
    '~/Desktop',  # Firefox creates this
    '~/.thumbnails',
    '~/.gconfd',
    '~/.gconf',
    '~/.local/share/gegl-0.2',
    '~/.FRD/log/app.log',  # FRD
    '~/.FRD/links.txt',  # FRD
    '~/.objectdb',  # FRD
    '~/.gstreamer-0.10',
    '~/.pulse',
    '~/.pulse-cookie',
    '~/.esd_auth',
    '~/.config/enchant',
    '~/.spicec',  # contains only log file; unconfigurable
    '~/.dropbox-dist',
    '~/.parallel',
    '~/.dbus',
    '~/ca2',  # WTF?
    '~/ca2~',  # WTF?
    '~/.distlib/',  # contains another empty dir, don't know which software creates it
    '~/.bazaar/',  # bzr insists on creating files holding default values
    '~/.bzr.log',
    '~/.nv/',
    # configured to be moved to ~/.cache/vim/viminfo, but it is still sometimes created...
    '~/.viminfo',
    '~/.npm/',  # npm cache
    '~/.java/',
    '~/.oracle_jre_usage/',
    '~/.jssc/',
    '~/.lsp4xml/',
    '~/.tooling/',
    '~/.webclipse/',
    '~/.swt/',
    '~/.sonar/',
    '~/.quake2rtx/',
    '~/.tox/',  # cache directory for tox
    '~/.pylint.d/',
    '~/.qute_test/',
    '~/.QtWebEngineProcess/',
    '~/.qutebrowser/',  # created empty, only with webengine backend
    '~/.asy/',
    '~/.cmake/',
    '~/.gnome/',
    '~/unison.log',
    '~/.texlive/',
    '~/.eclipse/',
    '~/.gradle/',
    '~/.m2/',
    '~/.pki/',
    '~/.yarn/',
    '~/.yarnrc/',
    '~/.mysql_history/',
    '~/.w3m/',
    '~/.subversion/',
    '~/.xsession-errors',
    '~/.xsession-errors.old',
    '~/.semantic-highlight-cache',
    '~/nvvp_workspace/',  # created empty even when the path is set differently in nvvp
]


def yesno(question, default="n"):
    """ Asks the user for YES or NO, always case insensitive.
    Returns True for YES and False for NO.
    """
    prompt = "%s (y/N) " % question

    ans = input(prompt).strip().lower()

    if not ans:
        ans = default

    if ans == "y":
        return True
    return False


def rmshit():
    print("Found shittyfiles:")
    found = []
    for file in shittyfiles:
        absf = os.path.expanduser(file)
        for filename in glob.iglob(absf, recursive=True):
            if os.path.exists(filename):
                found.append(filename)
                print("\t%s" % filename)

    if not found:
        print("No shitty files found :)")
        return

    if yesno("Remove all?", default="n"):
        for file in found:
            if os.path.isfile(file):
                os.remove(file)
            else:
                shutil.rmtree(file)
        print("All cleaned")
    else:
        print("No file removed")


if __name__ == '__main__':
    rmshit()
# vim: set ft=python
