# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

#  Wed Jan 09 2019 01:31
#  Dropping support after so much work:
#  Uses the chromium web engine
#  Ergo not even that light weight
#  Must protect firefox

from qutebrowser.config.config import ConfigContainer  # noqa: F401
# pylint: disable=C0111
from qutebrowser.config.configfiles import ConfigAPI  # noqa: F401

config = config  # type: ConfigAPI # noqa: F821 pylint: disable=E0602,C0103
c = c  # type: ConfigContainer # noqa: F821 pylint: disable=E0602,C0103

config.load_autoconfig()

# Bindings for normal mode
config.bind('d', 'scroll-page 0 0.5')
config.bind('e', 'scroll-page 0 -0.5')
config.bind('u', 'scroll-page 0 -0.5')
config.bind('q', 'tab-close')
config.bind('<Shift-t', 'open -t', mode='normal')
config.bind('<Alt-[>', 'tab-next', mode='normal')
config.bind('<Alt-]>', 'tab-prev', mode='normal')
config.bind('<Shift-k>', 'tab-next', mode='normal')
config.bind('<Shift-j>', 'tab-prev', mode='normal')
config.bind('<Ctrl-l>', 'messages', mode='normal')
config.bind('<Ctrl-r>', ':config-source', mode='normal')
config.bind('<space>tc', 'config-cycle colors.webpage.darkmode.enabled true false')

#  pip install --user tldextract
config.bind('<z><l>', 'spawn --userscript qute-pass')
config.bind('<z><u><l>', 'spawn --userscript qute-pass --username-only')
config.bind('<z><p><l>', 'spawn --userscript qute-pass --password-only')

c.content.pdfjs = True

c.spellcheck.languages = ["en-US"]

c.downloads.location.directory = '/home/reinaldo/Downloads'

c.url.start_pages = ['https://web.tabliss.io/']
c.url.default_page = 'https://web.tabliss.io/'
c.url.searchengines['DEFAULT'] = 'https://www.google.com/search?q={}'
c.url.searchengines['a'] = 'https://wiki.archlinux.org/?search={}'
c.url.searchengines['y'] = 'https://www.youtube.com/results?search_query={}'
c.url.searchengines[
    'w'] = 'https://secure.wikimedia.org/wikipedia/en/w/index.php?title=Special%%3ASearch&search={}'
c.url.searchengines['g'] = 'https://github.com/search?q={}&type=Repositories'

# colors
config.source('qutewal.py')
