# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

#  Wed Jan 09 2019 01:31
#  Dropping support after so much work:
#  Uses the chromium web engine
#  Ergo not even that light weight
#  Must protect firefox

import platform
import socket

from qutebrowser.config.config import ConfigContainer  # noqa: F401
# pylint: disable=C0111
from qutebrowser.config.configfiles import ConfigAPI  # noqa: F401

config = config  # type: ConfigAPI # noqa: F821 pylint: disable=E0602,C0103
c = c  # type: ConfigContainer # noqa: F821 pylint: disable=E0602,C0103

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
#  config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
#  config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
#  config.set('content.javascript.enabled', True, 'qute://*/*')

# Bindings for normal mode
config.bind('d', 'scroll-page 0 0.5')
config.bind('e', 'scroll-page 0 -0.5')
config.bind('u', 'scroll-page 0 -0.5')
config.bind('q', 'tab-close')
config.bind('<Shift-t', 'open -t', mode='normal')
config.bind('<Alt-[>', 'tab-next', mode='normal')
config.bind('<Alt-]>', 'tab-prev', mode='normal')
config.bind('<Shift-k>', 'tab-next', mode='normal')
config.bind('<Shift-j>', 'tab-prev', mode='normal')
config.bind('<Ctrl-l>', 'messages', mode='normal')
config.bind('<Ctrl-r>', ':config-source', mode='normal')
config.bind('<space>tc', 'config-cycle colors.webpage.darkmode.enabled true false')

#  pip install --user tldextract
config.bind('<z><l>', 'spawn --userscript qute-pass')
config.bind('<z><u><l>', 'spawn --userscript qute-pass --username-only')
config.bind('<z><p><l>', 'spawn --userscript qute-pass --password-only')

#  Will be discontinued
#  c.backend = "webkit"

c.content.pdfjs = True

c.spellcheck.languages = ["en-US"]

c.downloads.location.directory = '/home/reinaldo/Downloads'

c.url.start_pages = ['https://web.tabliss.io/']
c.url.default_page = 'https://web.tabliss.io/'
c.url.searchengines['DEFAULT'] = 'https://www.google.com/search?q={}'
c.url.searchengines['a'] = 'https://wiki.archlinux.org/?search={}'
c.url.searchengines['y'] = 'https://www.youtube.com/results?search_query={}'
c.url.searchengines[
    'w'] = 'https://secure.wikimedia.org/wikipedia/en/w/index.php?title=Special%%3ASearch&search={}'
c.url.searchengines['g'] = 'https://github.com/search?q={}&type=Repositories'

#  Privacy settings
#  Not available while using webengine backend
#  c.content.notifications = False
#  c.content.geolocation = False
#  c.content.canvas_reading = False
#  c.content.headers.custom = {
#  "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
#  }
#  c.content.webgl = False
#  c.content.javascript.enabled = False
#  c.content.cookies.accept = "never"
#  c.content.cookies.store = False

#  https://developer.chrome.com/apps/match_patterns
#  config.set('content.javascript.enabled', True, 'https://*.twitch.tv/*')
#  config.set('content.cookies.accept', "all", '*/twitch.tv*')

# colors
config.source('qutewal.py')
