#!/usr/bin/python

import imaplib
import base64
import os

finp = open('mail_info', 'rb')
fout = open('res', 'w')
#  TODO.RM-Sun Apr 02 2017 22:14: First enconde properly by calling base64.encode  
base64.decode(finp, fout)
info = fout.readline()

obj = imaplib.IMAP4_SSL('imap.gmail.com',993)
obj.login('rmolin88@gmail.com', info) # write your email and password
os.remove('~/.config/res')
obj.list()
obj.select('inbox', readonly = True)
#  obj.select()
print(len(obj.search(None, 'UnSeen')[1][0].split()))
#  >>> import base64
#  >>> print base64.b64encode("password")
#  cGFzc3dvcmQ=
#  >>> print base64.b64decode("cGFzc3dvcmQ=")
#  password
