#!/bin/sh
exec tail -n +3 $0
# First thing is to create a partition. Format it to ext2 and then run the 
# bootable usb created from the image.
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
# This file goes in /etc/grub.d/
#
# If you didn't create an sdcard image, remove the "SDCARD=/data/sdcard.img" part from the 3rd line (make sure you 
# don't remove anything else!) The above menu entry uses "eeepc" for androidboot.hardware, but you can replace it 
# with your hardware, depending on the ISO you've downloaded (use "asus_laptop" for the ASUS Laptop ISO, etc.) or use 
# "generic_x86". If you haven't installed Android-x86 4.0 RC1 but some other version, replace the lines containing 
# "android-4.0-RC1" with your version.
# For Android-x86 versions older than 4.0, use "androidboot_hardware" instead of "androidboot.hardware"
# But the most important thing you need to change in the menuentry is the partition on which you've installed 
# Android-x86, "(hd0,0)" in my example. If you don't know on which partition you've installed it, run the following 
# command in a terminal:
# `sudo fdisk -l`
#
# Once done do:
# `sudo chmod +x /etc/grub.d/40_custom`
# `sudo update-grub`
menuentry "Android-x86" {
set root='(hd0,7)'
linux /android-6.0-rc1/kernel quiet root=/dev/ram0 androidboot.hardware=android_x86_64 SRC=/android-6.0-rc1
initrd /android-6.0-rc1/initrd.img
}
