#!/bin/sh
# This command will break if you rename it to
# something containing "cmus".
# Adjust for your terminal name

if ! pgrep cmus ; then
	termite -e cmus&
	cmus-remote -u
else
  cmus-remote $1
fi
