#!/usr/bin/env bash
# Polybar is restarted by wal

# Send the mapping <leader>tn
if [[ -S /tmp/nvim.socket ]]; then
  nvim --server /tmp/nvim.socket --remote-send \
    '<c-\><c-n> tcn'
fi
if [[ -S /tmp/nvim_journal.socket ]]; then
  nvim --server /tmp/nvim_journal.socket --remote-send \
    '<c-\><c-n> tcn'
fi

if [[ -x $(command -v xfconf-query) ]]; then
  xfconf-query -c xsettings -p /Net/ThemeName -s "Adapta-Nokto"
  xfconf-query -c xsettings -p /Net/IconThemeName -s "Paper"
  xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "Bibata-Modern-DarkRed"
fi

# https://github.com/ankitects/anki/pull/1905/files
if [[ -x $(command -v gsettings) ]]; then
  gsettings set org.gnome.desktop.interface gtk-theme 'prefer-dark'
fi
# See here to change the cursor. Not straight forward.
# https://wiki.archlinux.org/title/Cursor_themes
# xfconf-query -c xsettings -p /Net/CursorName -s "CapitaineCursors"
