#!/bin/bash
# Polybar is restarted by wal

if [[ -f /usr/bin/nvr ]]; then
  if [[ -S /tmp/nvimsocket ]]; then
    /usr/bin/nvr --nostart --servername /tmp/nvimsocket -cc "ChangeColors sunrise"
  fi
  if [[ -S /tmp/neovim_journal ]]; then
    /usr/bin/nvr --nostart --servername /tmp/neovim_journal -cc "ChangeColors sunrise"
  fi
fi

if [[ -f /usr/bin/xfconf-query ]]; then
  xfconf-query -c xsettings -p /Net/ThemeName -s "Adapta-Nokto"
  xfconf-query -c xsettings -p /Net/IconThemeName -s "Paper"
fi
# See here to change the cursor. Not straight forward.
# https://wiki.archlinux.org/title/Cursor_themes
# xfconf-query -c xsettings -p /Net/CursorName -s "CapitaineCursors"
