#!/bin/bash
# Polybar is restarted by wal

/usr/bin/nvr --nostart --servername /tmp/nvimsocket -cc "ChangeColors day"
/usr/bin/nvr --nostart --servername /tmp/neovim_journal -cc "ChangeColors day"

xfconf-query -c xsettings -p /Net/ThemeName -s "Adapta"
xfconf-query -c xsettings -p /Net/IconThemeName -s "Paper"
# See here to change the cursor. Not straight forward.
# https://wiki.archlinux.org/title/Cursor_themes
# xfconf-query -c xsettings -p /Net/CursorName -s "CapitaineCursors"
