#!/bin/bash

/usr/bin/nvr --nostart --servername /tmp/nvimsocket -cc "ChangeColors day"
/usr/bin/nvr --nostart --servername /tmp/neovim_journal -cc "ChangeColors day"

# $HOME/.config/polybar/scripts/launch.sh
