#!/bin/bash
# Polybar is restarted by wal

if [[ -S /tmp/nvim.socket ]]; then
    /usr/bin/nvim --server /tmp/nvim.socket --remote-send ":ChangeColors sunrise<cr>"
fi
if [[ -S /tmp/nvim_journal.socket ]]; then
    /usr/bin/nvim --server /tmp/nvim_journal.socket --remote-send ":ChangeColors sunrise<cr>"
fi

if [[ -f /usr/bin/xfconf-query ]]; then
  xfconf-query -c xsettings -p /Net/ThemeName -s "Adapta"
  xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Light"
fi
# See here to change the cursor. Not straight forward.
# https://wiki.archlinux.org/title/Cursor_themes
# xfconf-query -c xsettings -p /Net/CursorName -s "CapitaineCursors"
